server:
  run-mode: 'debug'
  http-port: 8000
  read-timeout: 60
  write-timeout: 60
app:
  domain: localhost
  page-size: 10
  jwt-secret: shop
  prefix-url: 'http://127.0.0.1:8000'
  runtime-root-path: 'runtime/'
  image-save-path: 'upload/images/'
  # MB
  image-max-size: 5242880
  image-allow-exts: ['.jpg','.jpeg','.png']
  export-save-path: 'export/'
  qrcode-save-path: 'qrcode/'
  font-save-path: 'fonts/'
  log-save-path: 'logs/'
  Log-save-name: 'log'
  Log-file-ext: 'log'
  time-format: 20060102

api:
  search-product-ak: AK100523687952
  search-product-sk: W1WTYvJpfeH1YpUjTpeFbEx^DnpQ&35L

database:
  type: 'mysql'
  user: 'root'
  password: 'admin123'
  host: '127.0.0.1:3306'
  name: 'shop'
  table_prefix:

redis:
  host: '127.0.0.1:6379'
  password:
  idle_timeout: 200

kafka:
  hosts: ["127.0.0.1:9092"]

zap:
  log-filepath: 'runtime/logs'
  log-info-filename: 'info'
  log-warn-filename: 'warn'
  log-fiile-ext: 'log'
  log-console: true

wechat:
  app_id:
  app_secret:
  token: shop
  encoding_aes_key:

express:
  eBusinessId: 1607734
  appKey: 81f43a2e-f504-45c4-9b54-2637d59f8190
